### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by sultanahamer** [dhis2/dhis2-android-datacapture#13]
Hi Team,

Gradle build is failing and it says default config not found. Could you please provide information on how to setup the project. There seems to be some external dependencies.

**Comment by arazabishov** [comment]
In order to make master branch compiling, you need to clone https://github.com/dhis2/dhis2-android-sdk right next to the root directory of the DataCapture project.

**Comment by chingalo** [comment]
Hello,

I am also experience the same problem during build. it just says "Error:Configuration with name 'default' not found." I am using  Android studio V 1.5

My work space structure is 
.  ..  dhis2-android-datacapture  dhis2-android-sdk

**Comment by arazabishov** [comment]
Hello, are you trying to build master branch?

**Comment by chingalo** [comment]
Yes
