### ISSUE TITLE
Data elements with option sets show only a blank drop down list with no labels. 

### ISSUE THREAD

**Issue by ArchanaChillala** [dhis2/dhis2-android-datacapture#17]
I am currently using DHIS version 2.22 revision 21763.

![screenshot_2016-01-22-08-40-37_org dhis2 mobile](https://cloud.githubusercontent.com/assets/12930476/12606341/a2a78a0a-c4f2-11e5-911b-692643f5cc91.png)

**Comment by arazabishov** [comment]
Fixed.
