### ISSUE TITLE
Feature: Implement ability to record category options according to the combination of categories of the data set

### ISSUE THREAD

**Issue by Aleglise** [dhis2/dhis2-android-datacapture#20]
When accessing to a data set with a Combination of categories it is not possible to enter the category option value in the android app whereas it should be possible.

There are users in Rwanda who awould be delighted to capture data for data sets with a Combination of categories (which has actualy only on category)!

Thank you

**Comment by arazabishov** [comment]
Fixed in 1.6. You can find new version on GitHub and Google Play:

GitHub: https://github.com/dhis2/dhis2-android-datacapture/releases/tag/1.6
Google Play: https://play.google.com/store/apps/details?id=org.dhis2.mobile

**Comment by Aleglise** [comment]
Thank you !

![dsc03429](https://cloud.githubusercontent.com/assets/8737709/17440886/d8e7948e-5b2e-11e6-94f0-44062646911e.JPG)

**Comment by arazabishov** [comment]
Wow, thank you guys! :) Keeps me motivated.
