### ISSUE TITLE
DHIS2 android datacapture giving Network error 403

### ISSUE THREAD

**Issue by ssimkonda** [dhis2/dhis2-android-datacapture#36]
Hi,
DHIS2 android datacapture giving Network error 403 when am trying to save data. i have tried different devices and different internet connections. its able to pull data from the server but it cant save entries. please help.

**Comment by ifoche** [comment]
Hi @ssimkonda sorry but the app support goes through jira issues at jira.dhis2.org. Can you please create an issue there describing as much as possible your situation? If it's an issue related to current DHIS2 Android Apps the best is to use the Maintenance of Android Apps project, and in your case the DataCapture component. All the information that you can provide to replicate the problem will be very useful. Closing this issue

**Comment by ssimkonda** [comment]
Noted with thanks. Will contact Jira
