### ISSUE TITLE
Code is not Complete

### ISSUE THREAD

**Issue by i-sourabh** [dhis2/dhis2-android-datacapture#8]
After importing the project into android studio App is running fine in emulator but it is missing something , like user able to login into the MenuActivity but after that nothing happens , When we click on Choose Data Set app unfortunately stops. and also the screenshots on the play store are different . I want to see the complete code can you please provide me the complete code for Datacapture App.

App downloaded from play store is running fine.

**Comment by i-sourabh** [comment]
can anyone provide me the updated code as per playstore.

**Comment by arazabishov** [comment]
Hi Andy,

The source code for old version of datacapture app (the version you see in google play) is not in this repository. You should take a look here: https://code.launchpad.net/~araz-abishov-gsoc/dhis2/dhis2-android-app-1.5.5

**Comment by i-sourabh** [comment]
Thanks Araz for the source code , I have logged in with admin/district credentials and when I swipe the screen on Aggregate Report Activity, It always returns with bad Server Response and No forms found assigned for current user. Is it because may be there is no program assigned to the user or the server is not responding?

**Comment by i-sourabh** [comment]
When I Swipe the screen for update then no data comes on the screen. But Logcat shows data is fetching:
I/GET﹕ https://apps.dhis2.org/demo/api/me/assignedDataSets
I/200﹕ {"organisationUnits":{"jUb8gELQApl":{"id":"jUb8gELQApl","label":"Kailahun","level":2,"parent":"ImspTQPwCqd","dataSets":[{"id":"V8MHeZHIrcP","label":"Facility Assessment"}]},"eIQbndfxQMb":...............

Can you please give me the link for updated Code as per Playstore App as App from Playstore is working properly.
