### ISSUE TITLE
App unfortunately stops 

### ISSUE THREAD

**Issue by i-sourabh** [dhis2/dhis2-android-datacapture#9]
First of all thank you for providing the code for open access , I am trying it on the Android Studio and got some issues:

App stops in the following cases:
1. When User enters wrong data on the Login Screen.
2. When User selects Data Set option under Aggregate Reports , then also App unfortunately stops 
3. and when we choose following fields from the left drawer, nothing happened:
Data Entry: 
              Reports:  202 comes with blank screen
Profile:
           Account: only 301 toast comes

About: gives Relogin Page

I think this code is old one as when I tried the latest app from the Playstore it is running properly and it has only 3 elements on the left drawer.(Aggregate Reports , Profile and Logout) and also it shows Organisation Unit List for Level="2" only starting from BO, Bombali..so on which is different in case when i tried it on the studio.

Can you please provide me the latest updated code?

Thanks again.

**Comment by arazabishov** [comment]
This repository contains completely new version of datacapture app which is under active development. So you should take a look here (repository for google play version of app): https://code.launchpad.net/~araz-abishov-gsoc/dhis2/dhis2-android-app-1.5.5

**Comment by i-sourabh** [comment]
Thanks Araz for the source code , I have logged in with admin/district credentials and when I swipe the screen on Aggregate Report Activity, It always returns with bad Server Response and No forms found assigned for current user. Is it because may be there is no program assigned to the user or the server is not responding?
